#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Build the desktop-bundled Penglai runtime payload.

The payload is consumed by the Tauri desktop shell at first launch. It is not a
release artifact by itself; it is a resource directory that gets embedded into
the DMG/NSIS bundle.
"""
from __future__ import annotations

import argparse
import fnmatch
import hashlib
import json
import os
import shutil
import subprocess
import sys
import tarfile
import time
import platform
import urllib.request
from pathlib import Path


PBS_RELEASE = "20260510"
PBS_PYTHON_VERSION = "3.11.15"

CORE_DEP_SPECS = [
    "requests==2.34.2",
    "beautifulsoup4==4.14.3",
    "bottle==0.13.4",
    "aiohttp==3.13.5",
    "lark-oapi==1.6.8",
    "qrcode[pil]==8.2",
    "pillow==12.0.0",
    "pyyaml==6.0.3",
]
CORE_DEPS = [spec.split("==", 1)[0].split("[", 1)[0] for spec in CORE_DEP_SPECS]

PAYLOAD_README = """# Penglai Desktop Runtime Payload

This directory is generated by `packaging/build_desktop_runtime.py` during
desktop release builds.

The Tauri shell uses this payload first on initial runtime setup. Online
`install.sh` / `install.ps1` bootstrap is only a fallback when the packaged
payload is absent.
"""

EXCLUDE_DIRS = {
    ".git",
    ".github",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
    "__pycache__",
    "_internal",
    "audit",
    "build",
    "dist",
    "node_modules",
    "penglai-desktop-design",
    "secrets",
    "temp",
    "tmp",
}

EXCLUDE_FILES = {
    ".DS_Store",
    ".env",
    ".penglai-build.json",
    "auth.json",
    "model_responses.txt",
    "mykey.py",
    "mykey.json",
    "restore_commit.txt",
}

EXCLUDE_PATTERNS = (
    "*.egg-info",
    "*.key",
    "*.log",
    "*.p12",
    "*.pem",
    "*.pyc",
    "*.pyo",
    "*.zip",
    "*.exe",
    "mykey.py.bak*",
)


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def should_skip(path: Path, rel: str) -> bool:
    name = path.name
    if path.is_dir() and name in EXCLUDE_DIRS:
        return True
    if name in EXCLUDE_FILES:
        return True
    return any(fnmatch.fnmatch(name, pat) or fnmatch.fnmatch(rel, pat) for pat in EXCLUDE_PATTERNS)


def copy_source(source: Path, target: Path) -> None:
    if target.exists():
        shutil.rmtree(target)
    target.mkdir(parents=True, exist_ok=True)
    output_root = target.parent.resolve()
    for root, dirs, files in os.walk(source):
        root_path = Path(root)
        rel_root = root_path.relative_to(source)
        rel_root_str = "" if rel_root == Path(".") else rel_root.as_posix()
        dirs[:] = [
            d for d in dirs
            if not should_skip(root_path / d, f"{rel_root_str}/{d}".strip("/"))
            and (root_path / d).resolve() != output_root
        ]
        for filename in files:
            src = root_path / filename
            rel = (rel_root / filename).as_posix()
            if should_skip(src, rel):
                continue
            dst = target / rel
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dst)


def run(cmd: list[str], cwd: Path | None = None) -> str:
    proc = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, timeout=120)
    if proc.returncode != 0:
        raise SystemExit((proc.stdout or "") + (proc.stderr or ""))
    return (proc.stdout or "").strip()


def git_value(source: Path, args: list[str], default: str = "unknown") -> str:
    proc = subprocess.run(
        ["git", "-C", str(source), *args],
        capture_output=True,
        text=True,
        timeout=30,
    )
    if proc.returncode != 0:
        return default
    return (proc.stdout or "").strip() or default


def create_venv(source_payload: Path, python: str, pip_index: str) -> str:
    venv = source_payload / ".venv"
    if venv.exists():
        shutil.rmtree(venv)
    subprocess.check_call([python, "-m", "venv", str(venv)])
    if os.name == "nt":
        venv_python = venv / "Scripts" / "python.exe"
    else:
        venv_python = venv / "bin" / "python"
    subprocess.check_call([str(venv_python), "-m", "pip", "install", "--upgrade", "pip"])
    subprocess.check_call([
        str(venv_python),
        "-m",
        "pip",
        "install",
        "--disable-pip-version-check",
        "-i",
        pip_index,
        *CORE_DEP_SPECS,
    ])
    return str(venv_python.relative_to(source_payload))


def target_triple(target: str) -> str:
    mapping = {
        "mac-arm64": "aarch64-apple-darwin",
        "mac-aarch64": "aarch64-apple-darwin",
        "mac-x64": "x86_64-apple-darwin",
        "mac-x86_64": "x86_64-apple-darwin",
        "win-x64": "x86_64-pc-windows-msvc",
        "windows-x64": "x86_64-pc-windows-msvc",
    }
    try:
        return mapping[target]
    except KeyError:
        raise SystemExit(f"unknown standalone Python target: {target}")


def copy_python_bundle(bundle: Path, output: Path) -> None:
    dst = output / "python"
    if dst.exists():
        shutil.rmtree(dst)
    shutil.copytree(bundle, dst, symlinks=True)


def install_core_deps(python: Path, pip_index: str) -> None:
    subprocess.check_call([
        str(python),
        "-m",
        "pip",
        "install",
        "--no-warn-script-location",
        "--no-compile",
        "--disable-pip-version-check",
        "-i",
        pip_index,
        *CORE_DEP_SPECS,
    ])


def strip_python_bundle(python_dir: Path, target: str) -> None:
    stdlib = python_dir / "Lib" if target.startswith("win") else python_dir / "lib" / "python3.11"
    for rel in ("test", "tkinter", "idlelib", "turtledemo", "ensurepip"):
        shutil.rmtree(stdlib / rel, ignore_errors=True)
    if not target.startswith("win"):
        lib_dynload = stdlib / "lib-dynload"
        if lib_dynload.exists():
            for item in lib_dynload.glob("_tkinter*"):
                try:
                    item.unlink()
                except OSError:
                    pass
        for pattern in ("2to3*", "idle*", "pydoc*"):
            for item in (python_dir / "bin").glob(pattern):
                try:
                    item.unlink()
                except OSError:
                    pass


def safe_extract_tar(tf: tarfile.TarFile, target: Path) -> None:
    target_resolved = target.resolve()
    for member in tf.getmembers():
        member_path = (target / member.name).resolve()
        if member_path != target_resolved and target_resolved not in member_path.parents:
            raise SystemExit(f"unsafe python-build-standalone archive path: {member.name}")
    tf.extractall(target)


def valid_tar_gz(path: Path) -> bool:
    try:
        with tarfile.open(path, "r:gz") as tf:
            tf.getmembers()
        return True
    except (tarfile.TarError, OSError, EOFError):
        return False


def download_archive(url: str, archive: Path) -> None:
    tmp = archive.with_suffix(archive.suffix + ".part")
    tmp.unlink(missing_ok=True)
    urllib.request.urlretrieve(url, tmp)
    if not valid_tar_gz(tmp):
        tmp.unlink(missing_ok=True)
        raise SystemExit(f"downloaded python-build-standalone archive is invalid: {url}")
    tmp.replace(archive)


def create_standalone_python(
    output: Path,
    target: str,
    cache_dir: Path,
    pip_index: str,
    pbs_base_url: str,
    pbs_url_template: str,
) -> str:
    triple = target_triple(target)
    filename = f"cpython-{PBS_PYTHON_VERSION}+{PBS_RELEASE}-{triple}-install_only_stripped.tar.gz"
    if pbs_url_template:
        url = pbs_url_template.format(
            release=PBS_RELEASE,
            version=PBS_PYTHON_VERSION,
            triple=triple,
            filename=filename,
        )
    else:
        pbs_base_url = pbs_base_url.rstrip("/")
        url = f"{pbs_base_url}/{PBS_RELEASE}/{filename}"
    cache_dir.mkdir(parents=True, exist_ok=True)
    archive = cache_dir / filename
    if archive.exists() and not valid_tar_gz(archive):
        archive.unlink()
    if not archive.exists():
        download_archive(url, archive)

    python_dir = output / "python"
    if python_dir.exists():
        shutil.rmtree(python_dir)
    with tarfile.open(archive, "r:gz") as tf:
        safe_extract_tar(tf, output)
    if not python_dir.exists():
        raise SystemExit(f"python-build-standalone archive did not create {python_dir}")

    strip_python_bundle(python_dir, target)
    python_relpath = "python/python.exe" if target.startswith("win") else "python/bin/python3"
    python = output / python_relpath
    if not python.exists():
        raise SystemExit(f"standalone Python executable missing: {python}")
    install_core_deps(python, pip_index)
    return python_relpath


def dependency_lock(payload_root: Path, python_relpath: str) -> list[dict]:
    if not python_relpath:
        return []
    python = payload_root / python_relpath
    if not python.exists():
        return []
    proc = subprocess.run(
        [str(python), "-m", "pip", "list", "--format=json"],
        capture_output=True,
        text=True,
        timeout=120,
    )
    if proc.returncode != 0:
        raise SystemExit((proc.stdout or "") + (proc.stderr or ""))
    try:
        packages = json.loads(proc.stdout or "[]")
    except json.JSONDecodeError as exc:
        raise SystemExit(f"pip list did not return JSON: {exc}")
    rows = [
        {"name": str(pkg.get("name", "")).lower(), "version": str(pkg.get("version", ""))}
        for pkg in packages
        if str(pkg.get("name", "")).strip()
    ]
    return sorted(rows, key=lambda row: row["name"])


def remove_pycache(root: Path) -> None:
    for path in sorted(root.rglob("__pycache__"), reverse=True):
        if path.is_dir():
            shutil.rmtree(path, ignore_errors=True)


def build_manifest(
    output: Path,
    source: Path,
    python_relpath: str,
    python_kind: str,
    python_scope: str,
) -> dict:
    if python_relpath and python_scope == "source":
        python_abs = output / "source" / python_relpath
    elif python_relpath:
        python_abs = output / python_relpath
    else:
        python_abs = None
    python_version = run([str(python_abs), "-c", "import sys; print('.'.join(map(str, sys.version_info[:3])))"]) if python_abs else ""
    lock = dependency_lock(python_abs.parent if python_abs else output, python_abs.name if python_abs else "")
    remove_pycache(output)
    files = []
    for path in sorted(p for p in output.rglob("*") if p.is_file()):
        rel = path.relative_to(output).as_posix()
        if rel == "manifest.json":
            continue
        files.append({"path": rel, "sha256": sha256_file(path), "size": path.stat().st_size})
    return {
        "schema": 1,
        "kind": "penglai-desktop-runtime",
        "created_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "platform": {
            "os": sys.platform,
            "machine": platform.machine().lower(),
        },
        "source_branch": git_value(source, ["rev-parse", "--abbrev-ref", "HEAD"]),
        "source_commit": git_value(source, ["rev-parse", "--short=12", "HEAD"]),
        "python_kind": python_kind,
        "python_scope": python_scope,
        "python_relpath": python_relpath,
        "python_version": python_version,
        "core_deps": CORE_DEPS,
        "dependency_lock": lock,
        "entrypoints": {
            "cli": "source/penglai",
            "bridge": "source/frontends/desktop_bridge.py",
        },
        "files": files,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", default=".", help="Penglai source checkout")
    parser.add_argument("--output", required=True, help="payload output directory")
    python_group = parser.add_mutually_exclusive_group()
    python_group.add_argument("--with-venv", action="store_true", help="legacy transition path: create source/.venv")
    python_group.add_argument("--with-standalone-python", choices=["mac-arm64", "mac-x64", "win-x64"], help="download python-build-standalone and bundle it as runtime/python")
    python_group.add_argument("--python-bundle", help="copy an already prepared Python bundle directory into runtime/python")
    parser.add_argument("--python", default=sys.executable, help="python executable used to create the venv")
    parser.add_argument("--python-relpath", help="Python executable path relative to payload root when --python-bundle is used")
    parser.add_argument("--python-kind", default="standalone", help="manifest python_kind for --python-bundle")
    parser.add_argument("--pip-index", default=os.environ.get("PENGLAI_PIP_INDEX", "https://pypi.tuna.tsinghua.edu.cn/simple"))
    parser.add_argument("--pbs-cache", default=os.environ.get("PENGLAI_PBS_CACHE", ".cache/pbs"), help="python-build-standalone archive cache")
    parser.add_argument(
        "--pbs-base-url",
        default=os.environ.get("PENGLAI_PBS_BASE_URL", "https://github.com/astral-sh/python-build-standalone/releases/download"),
        help="base URL for python-build-standalone archives; override for domestic mirrors or internal caches",
    )
    parser.add_argument(
        "--pbs-url-template",
        default=os.environ.get("PENGLAI_PBS_URL_TEMPLATE", ""),
        help="full python-build-standalone URL template with {release}, {version}, {triple}, and {filename}",
    )
    args = parser.parse_args()

    source = Path(args.source).resolve()
    output = Path(args.output).resolve()
    source_payload = output / "source"

    if output.exists():
        shutil.rmtree(output)
    output.mkdir(parents=True, exist_ok=True)
    (output / "README.md").write_text(PAYLOAD_README, encoding="utf-8")
    copy_source(source, source_payload)

    python_relpath = ""
    python_kind = ""
    python_scope = ""
    if args.with_venv:
        rel = create_venv(source_payload, args.python, args.pip_index)
        python_relpath = rel.replace(os.sep, "/")
        python_kind = "venv"
        python_scope = "source"
    elif args.with_standalone_python:
        python_relpath = create_standalone_python(
            output,
            args.with_standalone_python,
            Path(args.pbs_cache).resolve(),
            args.pip_index,
            args.pbs_base_url,
            args.pbs_url_template,
        )
        python_kind = "standalone"
        python_scope = "runtime"
    elif args.python_bundle:
        copy_python_bundle(Path(args.python_bundle).resolve(), output)
        if args.python_relpath:
            python_relpath = args.python_relpath.replace(os.sep, "/")
        elif os.name == "nt":
            python_relpath = "python/python.exe"
        else:
            python_relpath = "python/bin/python3"
        python_kind = args.python_kind
        python_scope = "runtime"

    manifest = build_manifest(output, source, python_relpath, python_kind, python_scope)
    with (output / "manifest.json").open("w", encoding="utf-8") as f:
        json.dump(manifest, f, ensure_ascii=False, indent=2, sort_keys=True)
        f.write("\n")

    print(json.dumps({
        "ok": True,
        "output": str(output),
        "files": len(manifest["files"]),
        "platform": manifest["platform"],
        "python_relpath": python_relpath,
        "python_kind": python_kind,
        "python_scope": python_scope,
        "locked_deps": len(manifest["dependency_lock"]),
    }, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
